server:
  port: ${PORT:${SERVER_PORT:8084}}

spring:
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI:mongodb://localhost:27017/aipredictor}
      auto-index-creation: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope: email, profile
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"

          github:
            client-id: ${GITHUB_CLIENT_ID}
            client-secret: ${GITHUB_CLIENT_SECRET}
            scope: user:email
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"

          linkedin:
            client-id: ${LINKEDIN_CLIENT_ID}
            client-secret: ${LINKEDIN_CLIENT_SECRET}
            scope: r_liteprofile, r_emailaddress
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"

app:
  jwt-secret: 0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef
  jwt-expiration: 86400000   # 24 hours in ms
  ml-service-url: http://localhost:8001
